name: Ubuntu
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

########################################################################
## CONFIGURATION
########################################################################

env:
  IDRIS2_COMMIT: 2a05023e398e667edfd42901b8988ee0a217205a
  SCHEME: scheme

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Initialise variables
        run: |
          # Only deploy if the build follows from pushing to main
          if [[ '${{ github.ref }}' == 'refs/heads/main' ]]; then
             echo "FREX_DEPLOY=true" >> $GITHUB_ENV
          fi
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH

      # This caching step allows us to save a lot of building time by only
      # rebuilding Idris2 from boostrap if absolutely necessary
      - name: Cache Idris2
        uses: actions/cache@v2
        id: cache-idris2
        with:
          path: |
            ~/.idris2
          key: ${{ runner.os }}-${{ env.IDRIS2_COMMIT }}

      - name: Install Chez
        run: |
          sudo apt-get update
          sudo apt-get install -y chezscheme

      - name: Install Idris2
        if: steps.cache-idris2.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/idris-lang/idris2
          cd idris2
          git checkout ${{ env.IDRIS2_COMMIT }}
          make bootstrap && make install

      - name: Checkout idris-frex
        uses: actions/checkout@v2

      - name: Build package
        run: make build

      - name: Run tests
        run: make test INTERACTIVE=''

      - name: Build HTML doc
        run: make doc

      - name: Deploy HTML
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: ${{ success() && env.FREX_DEPLOY }}

        with:
          branch: gh-pages
          folder: build/docs/
